### ISSUE TITLE
Create private routes

### ISSUE THREAD

**Issue by horizon0708** [horizon0708/star-dev-chat#10]
Atm everyone can access all routes. 
- We want only logged in users to be able to access some routes, like `/profile`
- We want only public users to be able to access some routes, like `/signup` and `/signin`

## Tasks
- create two components `<PrivateRoute>` and `<RestrictedRoute>` that wraps the `<Route />` component of react-router-dom to add the following functionalities.
- `<PrivateRoute>` should redirect user to `/signin` if they are not logged in 
- `<RestrictedRoute>` should redirect user to `/` if they are logged in
- make `/profile`, be a private route
- make `/signin` and `/signup` be a restricted route

## Hint 

the routes would look like this
```jsx
// App.tsx
<PrivateRoute path={paths.profile} element={<Profile />} />
<RestrictedRoute path={paths.signin} element={<SignIn />} />
```

You can check whether the user is logged in by checking if the user object (`supabase.auth.user`) is null or not.

**Comment by behrouz2115** [comment]
And Also this Task, we did together.
