### ISSUE TITLE
Refactor the auth logic to use React Context

### ISSUE THREAD

**Issue by horizon0708** [horizon0708/star-dev-chat#20]
## Problem

The current implementation of detecting whether the user is logged in or not in Navbar and in Protected routes does not react to changes in the user's authentication state.

For example, signing out won't update the navbar until the whole app is reloaded.

This is because React is not aware of the changes. For React to "know" that the user's state has changed, (among many other options) we need to use React Context. 

So below
```javascript
const user = supabaseClient.auth.user() 
```

will need to change to something like

```javascript
const { user } = useAuthContext()
```

## Task

- Create a new React Context, _AuthContext_, that contains users' authentication status and updates when their status changes. 
- You will need to use `onAuthStateChange` (see https://ruanmartinelli.com/posts/supabase-authentication-react)
- Update old logic in the navbar and in protected routes to use the new AuthContext

**Comment by behrouz2115** [comment]
Hi,
I know how to use useContext but this time I got this problem "'children' is missing in props validation  react/prop-types".
