### ISSUE TITLE
Create Sign in Component

### ISSUE THREAD

**Issue by horizon0708** [horizon0708/star-dev-chat#6]
We have a Sign up form, but no Sign in form! 

##  Your tasks
1. Create a sign in form with sign in and password field. You must use `react-hook-forms` library to handle validation and submission (see `Signup.tsx` for examples).  Users should be able to sign in using the form.
2. When a user signs in, they should be redirected to "/"
3. Write tests for the sign in form. 

## client side validations for the forms
There should be validation errors for
- empty fields
- fields too short
- anything else you think is good

## writing tests
- I've written a sample test in `signup.test.js`. There are fair bit of new concept (especially with mocks) there. If you can't get the tests working, we can go through it later.

**Comment by behrouz2115** [comment]
I am Working on this task but still hard for me. in this part I have to send users' data ( email and password) to supabase then if users already have signed up can sign in?
else ask users to sign up first?
